# ###
# docker compose up --build -d
# docker compose exec saml composer install -n
# docker compose down
# ###
# http://localhost:80   # saml
# http://localhost:8080 # traefik
# http://localhost:8085 # cn=admin,dc=example,dc=org / adminp
# 
# saml => http://localhost/simplesaml/module.php/core/welcome
# ###

services:

  # 
  # docker compose exec saml cd /var/www && composer install -n
  # 
  saml:
    # https://github.com/richarvey/nginx-php-fpm/blob/main/Dockerfile
    # image: php:8.3-apache
    build:
      context: .
      dockerfile: ./docker/saml/Dockerfile
      target: base
    restart: always
    environment:
      # Set domain for let's encrypt
      DOMAIN: mydomain
      PGID: ${PGID}
      PUID: ${PUID}
      SSH_KEY: 'my-ssh-key'
    ports: [80:80]
    volumes:
      - ./docker/saml/apache/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      # override
      - ./saml/custom/config:/var/simplesamlphp_custom/config
      # - ./saml/simplesamlphp:/var/simplesamlphp
      # - ./saml/simplesamlphp/cert:/var/simplesamlphp/cert
      # - ./saml/simplesamlphp/metadata:/var/simplesamlphp/metadata
      # - ./saml/custom/public/index.php:/var/simplesamlphp/public/index.php
    # labels:
    #   - "traefik.http.routers.app.rule=Host(`localhost`)" # " && PathPrefix(`/api`)"

  # traefik:
  #   image: traefik:v3
  #   restart: always
  #   command:
  #     --api.insecure=true
  #     --providers.docker
  #     # --entrypoints.websecure.address=:443  # doesn't works for know ?
  #   ports:
  #     - "80:80"
  #     - "81:81"
  #     - "443:443"
  #     # The Web UI (enabled by --api.insecure=true)
  #     - "8080:8080"
  #   volumes:
  #     # So that Traefik can listen to the Docker events
  #     - /var/run/docker.sock:/var/run/docker.sock

  openldap:
    image: osixia/openldap:1.5.0
    restart: unless-stopped
    container_name: openldap
    environment:
      LDAP_BASE_DN: "dc=example,dc=org"
      LDAP_ORGANISATION: "Example Organization"
      LDAP_DOMAIN: "example.org"
      LDAP_ADMIN_PASSWORD: "adminp"
      LDAP_TLS: "false"
    ports:
      - 389:389
      - 636:636
    command: --copy-service
    volumes:
      - ./docker/ldap/bootstrap.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/50-bootstrap.ldif

  ldapadmin:
    # https://github.com/osixia/docker-phpLDAPadmin
    # Boot can take some time !
    # Login: cn=admin,dc=example,dc=org / adminp
    image: osixia/phpldapadmin:0.9.0
    restart: unless-stopped
    ports: [8085:80] # https://localhost:8085
    # hostname: phpldapadmin
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap  # docker container name
      - PHPLDAPADMIN_HTTPS=false
    depends_on:
      - openldap
