# ###
# docker compose up --build -d
# docker compose exec saml composer install -n
# docker compose down
# ###
# https://localhost     # SAML ssl
# ###
# http://localhost:8080 # traefik
# http://localhost:8085 # ldap: cn=admin,dc=example,dc=org / adminp
# 
# saml => http://localhost/simplesaml/module.php/core/welcome
# ###
#
# info:
# to have multi containers on https (443), use traefik
# ###

services:

  # 
  # docker compose exec saml cd /var/www && composer install -n
  # 
  saml-idp:
    build:
      context: .
      dockerfile: ./docker/saml/Dockerfile
      target: secure
    restart: always
    environment:
      # Set domain for let's encrypt
      DOMAIN: mydomain
      PGID: ${PGID}
      PUID: ${PUID}
    volumes:
      # 000-default.conf not used
      - ./docker/saml/apache/default-ssl-idp.conf:/etc/apache2/sites-enabled/default-ssl.conf
      - ./saml/idp:/var/simplesamlphp_custom
    labels:
      - "traefik.http.routers.app.rule=Host(`saml-idp`)"

  saml-sp1:
    build:
      context: .
      dockerfile: ./docker/saml/Dockerfile
      target: secure
    restart: always
    environment:
      # Set domain for let's encrypt
      DOMAIN: mydomain
      PGID: ${PGID}
      PUID: ${PUID}
    volumes:
      # 000-default.conf not used
      - ./docker/saml/apache/default-ssl-sp1.conf:/etc/apache2/sites-enabled/default-ssl.conf
      - ./saml/sp:/var/simplesamlphp_custom
    labels:
      - "traefik.http.routers.app.rule=Host(`saml-sp1`)"

  saml-sp2:
    build:
      context: .
      dockerfile: ./docker/saml/Dockerfile
      target: secure
    restart: always
    environment:
      # Set domain for let's encrypt
      DOMAIN: mydomain
      PGID: ${PGID}
      PUID: ${PUID}
    volumes:
      # 000-default.conf not used
      - ./docker/saml/apache/default-ssl.conf:/etc/apache2/sites-enabled/default-ssl.conf
      - ./saml/sp:/var/simplesamlphp_custom
    labels:
      - "traefik.http.routers.app.rule=Host(`saml-sp2`)"

  traefik:
    image: traefik:v3
    restart: always
    command:
      --api.insecure=true
      --providers.docker
      # --entrypoints.websecure.address=:443  # doesn't works for know ?
    ports:
      # - "80:80"
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock

  openldap:
    image: osixia/openldap:1.5.0
    restart: unless-stopped
    container_name: openldap
    environment:
      LDAP_BASE_DN: "dc=example,dc=org"
      LDAP_ORGANISATION: "Example Organization"
      LDAP_DOMAIN: "example.org"
      LDAP_ADMIN_PASSWORD: "adminp"
      LDAP_TLS: "false"
    ports:
      - 389:389
      - 636:636
    command: --copy-service
    volumes:
      - ./docker/ldap/bootstrap.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/50-bootstrap.ldif

  ldapadmin:
    # https://github.com/osixia/docker-phpLDAPadmin
    # Boot can take some time !
    # Login: cn=admin,dc=example,dc=org / adminp
    image: osixia/phpldapadmin:0.9.0
    restart: unless-stopped
    ports: [8085:80] # https://localhost:8085
    # hostname: phpldapadmin
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap  # docker container name
      - PHPLDAPADMIN_HTTPS=false
    depends_on:
      - openldap
