
# Use kubectl apply -f https://k8s.io/examples/pods/simple-pod.yaml
# sample: https://kubernetes.io/docs/tutorials/services/connect-applications-service/

apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    test: demo
    environment: production
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
      # good practice to define resource limits
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi