# ###
# cd docker/traefik.sample
# docker compose down --remove-orphans && docker compose -f docker-compose-traefik-sample.yml up --build -d
#
# https://zestedesavoir.com/billets/3355/traefik-v2-https-ssl-en-localhost/
# ###

services:

  tls-sample1:
    build: .
    volumes:
      - ./index.php:/var/specific/http/index.php
      - ./index_s.php:/var/specific/https/index.php
      - ./000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./default-ssl.conf:/etc/apache2/sites-enabled/default-ssl.conf
      - ./tls.sample.one.local.crt:/etc/ssl/certs/tls.sample.one.local.crt
      - ./tls.sample.one.local.key:/etc/ssl/private/tls.sample.one.local.key
    ports: 
      - 80:80
      - 443:443
    # labels:
      # - "traefik.enable=true"
      # - "traefik.http.routers.tlssampleone.rule=Host(`tls-sample.one.local`)"
      # - "traefik.http.routers.tlssampleone.tls=true"

  # https://doc.traefik.io/traefik/migration/v2-to-v3/
  # traefik:
  #   image: traefik:v2
  #   command:
  #     #- "--log.level=DEBUG"
  #     - "--api.insecure=true"
  #     - "--providers.docker=true"
  #     # - "--providers.docker.exposedbydefault=false"
  #     # - "--entryPoints.web.address=:80"
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #     - "8080:8080"
  #   volumes:
  #     - "/var/run/docker.sock:/var/run/docker.sock:ro"
  #     # On map la conf statique dans le conteneur
  #     # - ./traefik.yml:/etc/traefik/traefik.yml:ro
  #     # On map la conf dynamique statique dans le conteneur
  #     # - ./traefik.config.yml:/etc/traefik/config.yml:ro
  #     # On map les certificats dans le conteneur
  #     # on localhost, generated with "openssl req -x509 ......"
  #     - .:/etc/certs:ro

  #     # # Utilise la configuration du routeur "traefik" définie dans le fichier de configuration dynamique : ./traefik/config.yml
  #     # - "traefik.http.routers.traefik=true"

  # whoami:
  #   image: "traefik/whoami"
  #   container_name: "simple-service"
  #   labels:
  #     - "traefik.enable=true"
  #     # URL pour accéder à ce conteneur
  #     - "traefik.http.routers.whoami.rule=Host(`whoami.local`)"
  #     # Activation de TLS
  #     - "traefik.http.routers.whoami.tls=true"
  #     # Si le port est différent de 80, utilisez le service suivant:
  #     # - "traefik.http.services.<service_name>.loadbalancer.server.port=<port>"
  #     # - "traefik.http.routers.whoami.entrypoints=web"

  # hello-world:
  #   image: strm/helloworld-http
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.helloworld.rule=Host(`hello-world.local`)"
  #     - "traefik.http.routers.helloworld.tls=true"
