# kong-plugins.yaml
apiVersion: configuration.konghq.com/v1
kind: KongPlugin

metadata:
 name: grade-rate     # Must match name in Ingress annotation
 namespace: grade-demo
 annotations:
  kubernetes.io/ingress.class: kong
  
config:
 minute: 30     # Number of requests allowed per minute
 limit_by: consumer
 policy: local

plugin: rate-limiting
