# kong-secret.yaml
apiVersion: v1
kind: Secret

metadata:
 name: secret-gradepass               # Must match name referenced in KongConsumer
 namespace: grade-demo
 labels:
   konghq.com/credential: key-auth
  
type: Opaque
stringData:
 kongCredType: key-auth
 key: mygradepass               # Your chosen API key value