# kong-plugins.yaml
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
 name: <ratelimit-plugin-name>     # Must match name in Ingress annotation
 namespace: <your-namespace>
 annotations:
  kubernetes.io/ingress.class: kong
config:
 minute: <requests-per-minute>     # Number of requests allowed per minute
 limit_by: consumer
 policy: local
plugin: rate-limiting
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
 name: <auth-plugin-name>          # Must match name in Ingress annotation
 namespace: <your-namespace>
 annotations:
  kubernetes.io/ingress.class: kong
config:
 key_names:
   - apikey                        # Header name for the API key
 hide_credentials: true
plugin: key-auth