apiVersion: v1
kind: Secret
metadata:
 name: <secret-name>               # Must match name referenced in KongConsumer
 namespace: <your-namespace>
 labels:
   konghq.com/credential: key-auth
type: Opaque
stringData:
 kongCredType: key-auth
 key: <your-api-key>               # Your chosen API key value